### PR TITLE
Fixes #54: do not overwrite custom attributes

### LINKED ISSUE #54: do not ovewrite custom attributes e.g. {:rel="sponsored"}
Great plugin! Thanks for creating it.

Please, add a setting to skip manually set attributes.

For example, sometimes I publish sponsored links written in markdown as:
```[some text](https://www.sposnsor.com/){:rel="sponsored"}```

_jekyll-target-blank_ would remove `rel="sponsored"` and add the default `target="_blank" rel="noopener"`. This is not a desirable behavior. It should be `target="_blank" rel="sponsored noopener"` instead.

Sorry, I do not know how to develop a jekyll plugin, so I cannot PR this feature.

### PR DESCRIPTION
**Pull request by prplecake**
Keeps the existing `rel` attributes if they exist. Fixes #54

### CODE REVIEW

**Comment by WillPresley** [comment]
I just want to confirm that this fixes the issue for me as well. With rel="me" being used by Mastodon as a link verification mechanism, and Jekyll also being in that Fediverse world, I can see this being something that a lot of folks are struggling with. Thanks for the fix @prplecake! I hope it gets merged in soon

**Comment by prplecake** [comment]
Until this gets merged... which, at this point seems unlikely (Where's @keithmifsud??).

But one could point their Gemfile at the git repo to get the fixes. My repo is not going anywhere.

**Comment by keithmifsud** [comment]
Hi @prplecake ..thank for the PR. Some check are not passing and

**Comment by prplecake** [comment]
Superseded by #67

**Pull request closed without merging**
